/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: {
          base: 'rgb(var(--bg-base) / <alpha-value>)',
          surface: 'rgb(var(--bg-surface) / <alpha-value>)',
          elevated: 'rgb(var(--bg-surface-elevated) / <alpha-value>)',
          floating: 'rgb(var(--bg-surface-floating) / <alpha-value>)',
          hover: 'rgba(var(--bg-hover-rgb) / <alpha-value>)',
          active: 'rgba(var(--bg-active-rgb) / <alpha-value>)',
          disabled: 'rgba(var(--bg-disabled-rgb) / <alpha-value>)',
        },
        text: {
          primary: 'rgb(var(--text-primary) / <alpha-value>)',
          secondary: 'rgb(var(--text-secondary) / <alpha-value>)',
          muted: 'rgb(var(--text-muted) / <alpha-value>)',
          disabled: 'rgb(var(--text-disabled) / <alpha-value>)',
        },
        brand: {
          primary: 'rgb(var(--primary) / <alpha-value>)',
          'primary-hover': 'rgb(var(--primary-hover) / <alpha-value>)',
          'primary-active': 'rgb(var(--primary-active) / <alpha-value>)',
          'primary-fg': 'rgb(var(--primary-fg) / <alpha-value>)',
        },
        success: {
          DEFAULT: 'rgb(var(--success) / <alpha-value>)',
          fg: 'rgb(var(--success-fg) / <alpha-value>)',
          soft: 'var(--success-soft)',
        },
        warning: {
          DEFAULT: 'rgb(var(--warning) / <alpha-value>)',
          fg: 'rgb(var(--warning-fg) / <alpha-value>)',
          soft: 'var(--warning-soft)',
        },
        danger: {
          DEFAULT: 'rgb(var(--danger) / <alpha-value>)',
          fg: 'rgb(var(--danger-fg) / <alpha-value>)',
          soft: 'var(--danger-soft)',
        },
        info: {
          DEFAULT: 'rgb(var(--info) / <alpha-value>)',
          fg: 'rgb(var(--info-fg) / <alpha-value>)',
          soft: 'var(--info-soft)',
        },
        border: {
          DEFAULT: 'var(--border-default)',
          muted: 'var(--border-muted)',
          focus: 'var(--border-focus)',
          primary: 'var(--border-primary)',
        },
        glass: {
          bg: 'var(--glass-bg)',
          border: 'var(--glass-border)',
        }
      },
      borderRadius: {
        s: '6px',
        m: '8px',
        l: '12px',
        xl: '16px',
      },
      spacing: {
        '4px': '4px',
        '8px': '8px',
        '12px': '12px',
        '16px': '16px',
        '24px': '24px',
        '32px': '32px',
        '40px': '40px',
        '48px': '48px',
        '64px': '64px',
        '80px': '80px',
        '96px': '96px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        'display': ['3.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'hero': ['2.5rem', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        'h1': ['2rem', { lineHeight: '1.25', letterSpacing: '-0.015em' }],
        'h2': ['1.5rem', { lineHeight: '1.3', letterSpacing: '-0.015em' }],
        'h3': ['1.25rem', { lineHeight: '1.35', letterSpacing: '-0.010em' }],
        'h4': ['1.125rem', { lineHeight: '1.4', letterSpacing: '-0.005em' }],
        'body-lg': ['1rem', { lineHeight: '1.5', letterSpacing: '0' }],
        'body': ['0.875rem', { lineHeight: '1.5', letterSpacing: '0' }],
        'caption': ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.01em' }],
        'tiny': ['0.6875rem', { lineHeight: '1.4', letterSpacing: '0.02em' }],
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        micro: 'var(--ease-micro)',
        exit: 'var(--ease-exit)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '250ms',
        slow: '400ms',
        'page-transition': '500ms',
      },
      borderWidth: {
        DEFAULT: '3px',
        '0': '0',
        '1': '1px',
        '2': '2px',
        '3': '3px',
        '4': '4px',
        '8': '8px',
      },
      boxShadow: {
        s: '3px 3px 0 rgba(0, 0, 0, 1)',
        m: '6px 6px 0 rgba(0, 0, 0, 1)',
        l: '10px 10px 0 rgba(0, 0, 0, 1)',
        floating: '8px 8px 0 rgba(0, 0, 0, 1)',
        modal: '14px 14px 0 rgba(0, 0, 0, 1)',
      },
      zIndex: {
        behind: '-1',
        sidebar: '10',
        sticky: '20',
        topbar: '30',
        popover: '40',
        toast: '50',
        modal: '60',
        tooltip: '70',
      },
    },
  },
  plugins: [],
}
